export const CONTACTS_TABLE_COLUMN_DATA = [
  {
    title: "NAME & ROLE",
    dataIndex: "nameAndRole",
    key: "nameAndRole",
  },
  {
    title: "EMAIL",
    dataIndex: "email",
    key: "email",
  },
  {
    title: "CREATED AT",
    dataIndex: "createdAt",
    key: "createdAt",
  },
  {
    title: "",
    dataIndex: "actionButtons",
    key: "actionButtons",
  },
];

export const TABLE_PAGE_SIZE = 10;

export const CONTACTS_LIST = [
  {
    id: 1,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 2,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 3,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 4,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 5,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 6,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 7,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 8,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 9,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 10,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 11,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 12,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 13,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 14,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 15,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 16,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 17,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 18,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 19,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 20,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 21,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 22,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 23,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 24,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 25,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 26,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 27,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 28,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 29,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 30,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 31,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 32,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
];
