export const CONTACTS_TABLE_COLUMN_DATA = [
  {
    title: "NAME & ROLE",
    dataIndex: "nameAndRole",
    key: "nameAndRole",
  },
  {
    title: "EMAIL",
    dataIndex: "email",
    key: "email",
  },
  {
    title: "CREATED AT",
    dataIndex: "createdAt",
    key: "createdAt",
  },
  {
    title: "",
    dataIndex: "actionButtons",
    key: "actionButtons",
  },
];

export const TABLE_PAGE_SIZE = 10;

export const CONTACTS_LIST = [
  {
    id: 1,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 2,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 3,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 4,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 5,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 6,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 7,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 8,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 9,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 10,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 11,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 12,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 13,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 14,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 15,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 16,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 17,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 18,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 19,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 20,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 21,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 22,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 23,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 24,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 25,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 26,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 27,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 28,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 29,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 30,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 31,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
  {
    id: 32,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    createdAt: "Feb, 5, 2021",
  },
];
